config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  resources :animals

end

app/models/animal.rb
class Animal < ActiveRecord::Base
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def new
    @animal = Animal.new
  end

  def create
    animal = Animal.new(animal_params)
    if animal.save
      redirect_to animal_path(animal)
    else
      flash[:error] = animal.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:id])
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :description, :age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/new.html.erb
<%= form_for(@animal) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.submit "Create new animal" %>
<% end %>

app/views/animals/show.html.erb
<div id="animal_details">
  <p>Name: <%= @animal.name %>  </p>
  <p>Description: <%= @animal.description %>  </p>
  <p>Age: <%= @animal.age %>  </p>
</div>

app/views/home/home.html.erb
<%= link_to "Create a new little baby animal", new_animal_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LittleBabyAnimals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>